
include ../../inc/make.inc

TOP=nes_top
LOCAL_SRC = mmcm_hdmi.sv mmcm_nes_hdmi.sv $(TOP).sv 
DEVICE=xc7z010clg400-1
DEVICE_SHORT=xc7z010_1
HDL_SOURCE = $(HDMI_SOURCE) $(PPU_SOURCE) $(CPU_SOURCE) $(NES_SOURCE) $(CART_SOURCE) $(LOCAL_SRC)


include ../../inc/make.hw

