-verilog_define ROM_PATH="/home/jpdoane/dev/nesfpga/roms/"
-verilog_define PALFILE="/home/jpdoane/dev/nesfpga/roms/nes.mem"
-verilog_define PULSE_TABLE_FILE="/home/jpdoane/dev/nesfpga/roms/pulse_table.mem"
-verilog_define TND_TABLE_FILE="/home/jpdoane/dev/nesfpga/roms/tnd_table.mem"
