
include ../../inc/make.inc

DEVICE=xc7z010clg400-1
DEVICE_SHORT=xc7z010_1
TOP=audio_top
HDL_SOURCE = $(AUDIO_SOURCE) $(CLK_SOURCE) $(TOP).sv
CONSTRIANTS = $(CLOCK_XDC) $(ARTYZ7_XDC) 
 	
include ../../inc/make.hw

