
include ../../inc/make.inc

TOP=audio_tb
HDL_SOURCE = $(AUDIO_SOURCE) $(TOP).sv
# CUSTOMSIMARGS=-D'PALFILE="$(PROJ_ROOT)/roms/nes.mem"' -D'ROM_PATH="$(PROJ_ROOT)/roms/smb_ppu/"'

include ../../inc/make.sim

